# Generated by Django 4.1.12 on 2023-10-22 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchrecord',
            unique_together={('user_profile', 'video', 'time')},
        ),
    ]
