# Generated by Django 4.1.12 on 2023-10-30 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='user_id',
        ),
    ]
