# Generated by Django 4.1.12 on 2023-10-22 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_alter_watchrecord_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.AddField(
            model_name='category',
            name='custom_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
